### ISSUE TITLE
Fatal Error because AuthProvider is Missing

### ISSUE THREAD

**Issue by CameronPorter95** [Iterable/swift-sdk#380]
After updating to Xcode 12, on startup now getting this error on iOS 14 devices: 
`Fatal error: authProvider is missing: file IterableSDK/ApiClient.swift, line 222`

**Comment by tapashmajumder** [comment]
We are not seeing this. Can you please provide more details? Which version of SDK are you using? Did the same version of SDK work with iOS 13?

We have seen this error happen when `IterableAPI .initialize` is called multiple times.

**Comment by CameronPorter95** [comment]
I've noticed it wasn't happening on 6.1.0 but it is on 6.2.10. 
After more attempts I've seen that it still happens on iOS 13 as well as 14

**Comment by tapashmajumder** [comment]
Please have your customer service rep create a ticket with us. Please include all relevant details in the ticket including:
1. When the crash is happening
2. Is there an easy way to repro this issue on our end? Since we do not have access to your codebase.
3. Are you using Obj-C or Swift? Or are you using React Native SDK.
4. How are you initializing our SDK? That is, `IterableAPI.initialize` code..

**Comment by tapashmajumder** [comment]
Please see note above

**Comment by jpeckner** [comment]
I'm seeing the exact same issue (down to the line number), even though I've verified via `print` statements that my app calls `IterableAPI.initialize(...)` before it calls `IterableAPI.register(...)`. Setup details:

- iOS version: 14.0.1
- Xcode version: 12.0.1
- Iterable SDK version: 6.2.11 (installed via Cocoapods)

It seems like the `authProvider` instance must be getting deallocated before the line with the `fatalError()` is called.

**Comment by jpeckner** [comment]
I had this same issue, and found that use SDK version 6.2.12-beta1 fixed it. Hope it gets fully released soon!

**Comment by tapash-majumder** [comment]
Hi @CameronPorter95 @jpeckner we are taking this issue seriously. We would like to understand the problem. But we can't resolve this issue without more details from you. Please see my comment earlier regarding opening a support ticket. I am copying this here again for quick reference.

1. We have seen this issue when `IterableAPI.initialize` is called multiple times. It is supposed to be initialized only once
2. Is there an easy way to repro this issue on our end? Since we do not have access to your codebase.
3. Are you using Obj-C or Swift? Or are you using React Native SDK.
4. How are you initializing our SDK? That is, IterableAPI.initialize code..

Please have your customer service rep open a support ticket and provide us more details. 

Thanks!

**Comment by jpeckner** [comment]
Aha, it looks like accidentally calling IterableAPI.initialize() more than once was the issue! Thanks for clearing that up.

Going forward, I’d highly suggest refactoring the SDK so it never intentionally crashes, including this particular fatalError(). I get that reaching that line means that the SDK is in an unusable state, but that doesn’t mean it should decide to take my whole app down with it. I’d much rather that the SDK reported an error back to my app, and then gracefully shut itself down. An assertionFailure() would also be fine, since that wouldn’t crash App Store builds.

Good blog post regarding this situation in another SDK: https://www.bugsnag.com/blog/sdks-should-not-crash-apps

**Comment by tapash-majumder** [comment]
@jpeckner We have already made the fatalError fix you suggested. It will take some time before we release our next version with it.
