### ISSUE TITLE
The same request, why different results in different time periods?

### ISSUE THREAD

**Issue by Cienet-Mahui** [Iterable/swift-sdk#556]
Hello, I'm sending notifications to our app with the same userid at different times, sometimes it fails and sometimes it succeeds. Can you help me find out why?
<img width="757" alt="Screen Shot 2022-05-17 at 10 05 44" src="https://user-images.githubusercontent.com/78529901/168965349-4c4dcb53-7459-477f-9eb4-d0b387ce5b13.png">
<img width="748" alt="Screen Shot 2022-05-17 at 10 05 57" src="https://user-images.githubusercontent.com/78529901/168965369-8484cd65-f673-4469-b60e-0832668bae06.png">

iterableApi:
https://api.iterable.com/api/push/target?apiKey=c7e470422a704d73b118ed21249a10b7
request:
`{
	"campaignId": 2027117,
	"recipientUserId": "apple|000489.51d241bf9c1d4457973ff40dea6fa6ed.0618"
}`

response:
`{
    "msg": "Campaign 2027117 - Sent triggered message to: test@gami.com",
    "code": "Success",
    "params": null
}`
`{
    "msg": "No user exists with userId apple|000489.51d241bf9c1d4457973ff40dea6fa6ed.0618",
    "code": "BadParams",
    "params": null
}`

**Comment by roninopf** [comment]
Hi @Cienet-Mahui , can you contact your CSM for this? We reserve GitHub issues for bugs, in particular.

I've also told our support team to reset your API key as this is a public open source repo.

**Comment by Mturner005** [comment]
Hello @Cienet-Mahui.  First, I'd just like to point out that you've shared an image that has an API key to your Iterable project.  There isn't really a way for us to redact your image, so I'd recommend you disable that API key ASAP in your Iterable project and start using a new one.

Also, could you please open up a support ticket: [](https://support.iterable.com/hc/en-us/requests/new) So that we can help dig into this issue further for you?
